### ISSUE TITLE
>: Don't have lyrics right now :< 

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [TimoLin/SpotifyLyrics#1]
One of us here is wrong!
i used same song that in your example but yet, still no lyrics 
![Screenshot 2020-09-15 09:55:54](https://user-images.githubusercontent.com/28893833/93182256-c5af0680-f739-11ea-83be-f8472b22a4ee.png)

**Comment by TimoLin** [comment]
Dear EsmailELBoBDev2,

Sorry for my late reply. 
This error message means the lyrics crawler can't get lyrics frome 'Mini lyrics'. Maybe it's because the [`_minilyrics` crawler](https://github.com/TimoLin/SpotifyLyrics/blob/master/lyrics.py) is too old for the 'Mini lyrics' website, I don't know and sorry I don't have much time to fix this.

This script shows synced lyrics of the current playing song, which means we need to get the lyrics with time information. Like this:
```
[00:16.53]We were both young when I first saw you
[00:20.16]I close my eyes and the flashback starts
[00:23.76]I'm standing there on a balcony in summer air
```
In the current script, only the lyrics from source `Mini Lyrics` are with time information. The other lyric sources like `Wikia`, `Musixmatch`, `Songmeanings`, etc , don't have the time information. You can see these crawlers in [services.py](https://github.com/TimoLin/SpotifyLyrics/blob/master/services.py).

To fix this bug, we can use other lyrics sources which is more stable, like QQ, netease, xiami, ... The python crawlers for those sources can be found in GitHub. For example, you can check this project  https://github.com/SimonIT/spotifylyrics/blob/master.

Timo

**Comment by TimoLin** [comment]
Change this line if you use another lyrics crawler:
https://`github.com/TimoLin/SpotifyLyrics/blob/e41a7cc7cbd81375fb27a92fcf11bbcfc5a922c4/SpotifyLyrics.py#L55

**Comment by TimoLin** [comment]
Change this line if you use another lyrics crawler:  
https://github.com/TimoLin/SpotifyLyrics/blob/e41a7cc7cbd81375fb27a92fcf11bbcfc5a922c4/SpotifyLyrics.py#L55

**Comment by EsmailELBoBDev2** [comment]
i'm sorry timo :c 
I'm new to python and your project looks big but i will try what you said and tell you the updates but if you got the time don't forget me as its your project and it will be so easy for you to fix it fast
